# Dependabot configuration for Caxton
# Keep dependencies up to date automatically

version: 2
updates:
  # Rust/Cargo dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "jwilger"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      security-updates:
        patterns:
          - "*audit*"
          - "*security*"
          - "*crypto*"
          - "*tls*"
          - "*ssl*"
        update-types:
          - "security-update"
      dev-dependencies:
        patterns:
          - "quickcheck*"
          - "proptest*"
          - "criterion*"
          - "cargo-*"
        dependency-type: "development"
      performance-deps:
        patterns:
          - "tokio*"
          - "wasmtime*"
          - "serde*"
          - "tracing*"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "jwilger"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Docker dependencies (if any Dockerfile exists)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "jwilger"
    commit-message:
      prefix: "docker"
      include: "scope"

  # Ruby dependencies for Jekyll site
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "jwilger"
    commit-message:
      prefix: "deps"
      include: "scope"
