# This bacon.toml file is built and maintained by bacon itself.
# Bacon repository: https://github.com/Canop/bacon
# Complete help on configuration: https://dystroy.org/bacon/config/

default_job = "nextest"

[jobs.nextest]
command = ["cargo", "nextest", "run", "--color=always"]
need_stdout = true

[jobs.nextest-lib]
command = ["cargo", "nextest", "run", "--lib", "--color=always"]
need_stdout = true

[jobs.nextest-integration]
command = ["cargo", "nextest", "run", "--tests", "--color=always"]
need_stdout = true

[jobs.nextest-nocapture]
command = ["cargo", "nextest", "run", "--nocapture", "--color=always"]
need_stdout = true

[jobs.check]
command = ["cargo", "check", "--color=always"]
need_stdout = false

[jobs.clippy]
command = ["cargo", "clippy", "--no-deps", "--color=always", "--", "-D", "warnings"]
need_stdout = false

[jobs.test-std]
command = ["cargo", "test", "--color=always"]
need_stdout = true
