[package]
name = "caxton"
version = "0.1.0"
edition = "2021"
authors = ["John Wilger <john@johnwilger.com>"]
license = "MIT"
description = "A type-driven multi-agent orchestration platform with WebAssembly isolation and FIPA messaging"
documentation = "https://docs.rs/caxton"
homepage = "https://jwilger.github.io/caxton/"
repository = "https://github.com/jwilger/caxton"
readme = "README.md"
keywords = ["multi-agent", "webassembly", "fipa", "orchestration", "agents"]
categories = ["concurrency", "web-programming", "wasm", "api-bindings"]
rust-version = "1.70"
exclude = [
    "coordination/",
    "memory/",
    "claude-flow*",
    "CLAUDE.md",
    "DIALOGUE.md",
    "WORK.md",
    "backupclaudemd.bak",
    "*.log",
    ".swarm/"
]

[dependencies]
# Async runtime
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"

# Serialization and data handling
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bytes = "1.7"
fastrand = "2.1"

# Date and time handling
chrono = { version = "0.4", features = ["serde"] }

# UUID generation and handling
uuid = { version = "1.0", features = ["v4", "v5", "serde"] }

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# WebAssembly runtime with optimizations
wasmtime = { version = "24.0", features = ["async", "pooling-allocator", "component-model", "parallel-compilation"], optional = true }
wasmtime-wasi = { version = "24.0", optional = true }

# Performance and monitoring
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
metrics = "0.23"

# High-performance data structures
smallvec = "1.13"
ahash = "0.8"
once_cell = "1.19"

# Threading and synchronization
arc-swap = "1.6"
dashmap = "5.5"
parking_lot = "0.12"

# System metrics
sysinfo = "0.30"

[features]
default = ["wasm-runtime"]
wasm-runtime = ["wasmtime", "wasmtime-wasi"]

[dev-dependencies]
# Property-based testing
quickcheck = "1.0"
quickcheck_macros = "1.0"
proptest = "1.4"

# Benchmarking and testing
criterion = { version = "0.5", features = ["html_reports", "async_tokio"] }
wat = "1.0"
tokio-test = "0.4"

[[example]]
name = "lifecycle_example"
path = "examples/lifecycle_example.rs"
