[package]
name = "caxton"
version = "0.1.4"
edition = "2024"
authors = ["John Wilger <john.wilger@gmail.com>"]
description = "A secure WebAssembly runtime for multi-agent systems"
license = "MIT OR Apache-2.0"
repository = "https://github.com/jwilger/caxton"
homepage = "https://github.com/jwilger/caxton"
documentation = "https://docs.rs/caxton"
readme = "README.md"
keywords = ["wasm", "agent", "runtime", "sandbox", "distributed"]
categories = ["wasm", "concurrency", "network-programming"]

[lints.rust]
warnings = "deny"
missing_docs = "warn"
rust_2018_idioms = "warn"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
# Don't warn about dependency issues we can't control
multiple_crate_versions = "allow"
# These are too strict for a prototype
must_use_candidate = "allow"
missing_const_for_fn = "allow"
module_name_repetitions = "allow"

[dependencies]
wasmtime = "27.0"
wasmtime-wasi = "27.0"
tokio = { version = "1.42", features = ["full"] }
anyhow = "1.0"
thiserror = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
async-trait = "0.1"
uuid = { version = "1.11", features = ["v4", "serde"] }
dashmap = "6.1"
bytes = "1.9"
wat = "1.223"
nutype = { version = "0.6.2", features = ["serde"] }
num_cpus = "1.16"
futures = "0.3"
rust_decimal = "1.33"

[dev-dependencies]
approx = "0.5"
criterion = "0.5"
tempfile = "3.14"
test-log = "0.2"
proptest = "1.6"
wat = "1.223"

[[bin]]
name = "caxton"
path = "src/main.rs"

[lib]
name = "caxton"
path = "src/lib.rs"


[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[profile.bench]
inherits = "release"
