[package]
name = "caxton"
version = "0.1.4"
edition = "2024"
authors = ["John Wilger <john.wilger@gmail.com>"]
description = "A secure WebAssembly runtime for multi-agent systems"
license = "MIT OR Apache-2.0"
repository = "https://github.com/jwilger/caxton"
homepage = "https://github.com/jwilger/caxton"
documentation = "https://docs.rs/caxton"
readme = "README.md"
keywords = ["wasm", "agent", "runtime", "sandbox", "distributed"]
categories = ["wasm", "concurrency", "network-programming"]

[lints.rust]
warnings = "deny"
missing_docs = "warn"
rust_2018_idioms = "warn"

[lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
# Don't warn about dependency issues we can't control
multiple_crate_versions = "allow"
# These are too strict for a prototype
must_use_candidate = "allow"
missing_const_for_fn = "allow"
module_name_repetitions = "allow"

[dev-dependencies]
approx = "0.5"
criterion = "0.5"
tempfile = "3.14"
test-log = "0.2"
proptest = "1.6"
toml = "0.8"
wat = "1.223"

[[bin]]
name = "caxton"
path = "src/main.rs"

[lib]
name = "caxton"
path = "src/lib.rs"


[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[profile.bench]
inherits = "release"

[dependencies]
anyhow = "1.0.98"
async-trait = "0.1.88"
bytes = "1.10.1"
dashmap = "6.1.0"
futures = "0.3.31"
num_cpus = "1.17.0"
nutype = { version = "0.6.2", features = ["serde"] }
rust_decimal = "1.37.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
sqlx = { version = "0.8", default-features = false, features = ["sqlite", "runtime-tokio-rustls"] }
thiserror = "2.0.12"
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "json"] }
uuid = { version = "1.17.0", features = ["v4", "serde"] }
wasmtime = "35.0.0"
wasmtime-wasi = "35.0.0"
wat = "1.223"
