# Example configuration agent for testing
# This provides a minimal working agent for development

name = "HelloWorld"
version = "1.0.0"
description = "A simple greeting agent for testing"

# Capabilities this agent provides
capabilities = ["greeting", "testing"]

# MCP tools this agent can use (when implemented)
tools = ["echo"]

# Memory configuration
[memory]
enabled = true
scope = "agent-only"
auto_store = false

# Agent parameters
[parameters]
default_greeting = "Hello from Caxton!"
max_message_length = 1000

# System prompt for the agent
system_prompt = '''
You are a friendly greeting agent named HelloWorld.
Your purpose is to provide simple greetings and help test the Caxton system.
Always be polite and helpful in your responses.
'''

# Template for user interactions
user_prompt_template = '''
User request: {{request}}

Please respond with a friendly greeting or help message.
Keep responses concise and helpful.
'''

# Documentation for this agent
documentation = '''
# HelloWorld Agent

This is a simple test agent that demonstrates the Caxton configuration-driven agent system.

## Capabilities
- Provides friendly greetings
- Responds to basic test queries
- Demonstrates agent configuration patterns

## Usage
This agent is primarily for development and testing purposes.
'''
