[build]
rustflags = ["-D", "warnings"]

[alias]
# Clippy with deny warnings (no-deps to avoid dependency build script issues)
clippy-strict = "clippy --no-deps -- -D warnings"

# Test with deny warnings
test-strict = "test -- --deny warnings"
